version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: reservaMentor
      POSTGRES_DB: reservamentor_db
    ports:
      - 5433:5432

  server:
    image: reservamentorsv:tag
    build:
      context: .
      dockerfile: Dockerfile 
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod

    ports:
      - "8080:8080"